### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dm4uz3**

### CODE REVIEW

**Comment by Tvde1** [comment]
monet

**Comment by Tvde1** [comment]
csnt

**Comment by xmatmen** [comment]
monet

**Comment by xmatmen** [comment]
csnt

**Comment by NCPlayz** [comment]
monet

**Comment by NCPlayz** [comment]
csnt

**Comment by dm4uz3** [comment]
monet was on purpose

**Comment by level6ascend** [comment]
hi all from discord say 1 for pennis and dicke and also balls

**Comment by level6ascend** [comment]
and also fuck you

**Comment by xmatmen** [comment]
already done (no u)

**Pull request closed without merging**
