### PR TITLE
Create doublexd

### PR DESCRIPTION
**Pull request by jeffcubed**
no u

### CODE REVIEW

**Comment by xmatmen** [comment]
what does this do, send screenshots xd

**Comment by xmatmen** [comment]
oops didnt mean to close

**Comment by jeffcubed** [comment]
it makes a double xd

**Comment by xmatmen** [comment]
thats not a screenshot smh

**Comment by dm4uz3** [comment]
http://i.imgur.com/h4W0m6J.jpg

**Comment by xmatmen** [comment]
no u

**Comment by dm4uz3** [comment]
but that's a screenshot

**Comment by xmatmen** [comment]
ill ban you

**Comment by dm4uz3** [comment]
*hides in fear*

**Comment by James76931** [comment]
chef

**Pull request closed without merging**
