### PR TITLE
Updating the Readme.MD

### PR DESCRIPTION
**Pull request by RobStyling**
But its not finished yet. I am working on it

### CODE REVIEW

**Comment by RobStyling** [comment]
merge when?

**Comment by xmatmen** [comment]
neverTM

**Comment by dm4uz3** [comment]
™

**Comment by xmatmen** [comment]
dude, this is a meme bot, we dont need a proper description

**Comment by dm4uz3** [comment]
rood

**Comment by xmatmen** [comment]
no u

**Pull request closed without merging**
